version: '3.3'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./.env
  zoncord-id:
    image: zoncord.azurecr.io/zoncord-id
    restart: always
    build:
      context: ../.
      dockerfile: ./build/Dockerfile
    command: go run cmd/main.go
    ports:
      - 8080:8080
    env_file:
      - ./.env
    depends_on:
      - db
