version: '3.3'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env
  zoncord-id:
    image: zoncord.azurecr.io/zoncord-id
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: go run main.go
    ports:
      - 8080:8080
    env_file:
      - ./.env
    depends_on:
      - db
